apiVersion: v1
kind: Service
metadata:
  name: nifi-hs
  labels:
    app: my-nifi
spec:
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
      name: ui
    - protocol: TCP
      targetPort: 9088
      port: 9088
      name: node-protocol-port
    - protocol: TCP
      targetPort: 8888
      port: 8888
      name: s2s
  clusterIP: None
  selector:
    app: my-nifi
---
apiVersion: v1
kind: Service
metadata:
  name: nifi-cs
  labels:
    app: my-nifi
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      name: nifiui
      nodePort: 30008
  selector:
    app: my-nifi
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: nifi-pdb
spec:
  selector:
    matchLabels:
      app: my-nifi
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-nifi
spec:
  selector:
    matchLabels:
      app: my-nifi
  serviceName: nifi-hs
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: my-nifi
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - my-nifi
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nifi-container
          image: apache/nifi:latest
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 22
              name: ssh
          resources:
            requests:
              cpu: ".5"
              memory: ".5Gi"
            limits:
              cpu: "1"
          env:
            - name: VERSION
              value: "1.12.0"
            - name: NIFI_CLUSTER_IS_NODE
              value: "true"
            - name: NIFI_CLUSTER_NODE_PROTOCOL_PORT
              value: "9088"
            - name: NIFI_ELECTION_MAX_CANDIDATES
              value: "1"
            - name: NIFI_ELECTION_MAX_WAIT
              value: "5 mins"
            - name: NIFI_ZK_CONNECT_STRING
              value: "zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181"
