apiVersion: v1
kind: Service
metadata:
  name: nifi-service

spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30008
  selector:
    app: nifi-app
    type: front-end