apiVersion: v1
kind: Service
metadata:
  name: nifi-service
spec:
  selector:
    app: my-nifi
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
      name: ui
    - protocol: TCP
      targetPort: 9088
      port: 9088
      name: node-protocol-port
    - protocol: TCP
      targetPort: 8888
      port: 8888
      name: s2s
  type: LoadBalancer
---
apiVersion: v1
kind: Deployment
metadata:
  name: nifi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nifi
  template:
    metadata:
      labels:
        app: my-nifi
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: nifi-container
          image: apache/nifi:latest
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 22
              name: ssh
          resources:
            requests:
              cpu: ".5"
              memory: "3Gi"
            limits:
              cpu: "1"
          env:
            - name: VERSION
              value: "1.9"
            - name: NIFI_CLUSTER_IS_NODE
              value: "true"
            - name: NIFI_CLUSTER_NODE_PROTOCOL_PORT
              value: "9088"
            - name: NIFI_ELECTION_MAX_CANDIDATES
              value: "1"
            - name: NIFI_ZK_CONNECT_STRING
              value: "zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181"