apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-nifi
  namespace: nifi
  labels:
    app: my-nifi
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: my-nifi
  template:
    metadata:
      namespace: nifi
      labels:
        app: my-nifi
    spec:
      containers:
        - name: my-nifi
          image: apache/nifi:1.11.3
          args:
            ["sh /nifi/nifi_start.sh"]
          ports:
            - containerPort: 8443
              name: ca-client-port
          command:
            - bash
            - -c
            - |
              ../nifi-toolkit-current/bin/tls-toolkit.sh server -c my-nifi-rs -t Welcome2018nifihdf3
---
# Create service for the my-nifi replica set
apiVersion: v1
kind: Service
metadata:
  name: my-nifi-rs
  namespace: nifi
  labels:
    app: my-nifi
spec:
  ports:
    - port: 8443
      name: ca-client-port
      targetPort: 8443
  selector:
    app: my-nifi