apiVersion: v1
kind: Pod
metadata:
  name: nifi-pod
  labels:
    app: nifi-app
    type: front-end

spec:
  containers:
    - name: nifi-container
      image: apache/nifi:latest
      ports:
        - containerPort: 8080
          protocol: TCP